# Generated by Django 4.2.3 on 2023-07-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(default='https://scholastic.asia/sites/all/themes/scholastic_asia/images/default-book.png', max_length=500),
        ),
    ]
